Vagrant::Config.run do |config|
  config.vm.box = "lucid32"
  config.vm.customize do |vm|
    vm.memory_size = 1024
  end

  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = ["../cookbooks"]
    chef.log_level = :debug
    chef.add_recipe "apt"
    chef.add_recipe "git"
    chef.add_recipe "monit"

    chef.json.merge!({
                       :monit => {
                         :start_delay => 45,
                         :interval => 30,
                         :web => {
                           :enabled => true
                         }}
                     })

    #this prints out the vagrant config to a `dna.json` file that we
    #can upload to an EC2 instance and use with `chef-solo`.
    require 'json'
    open('dna.json', 'w'){|f| f.write chef.json.to_json}

  end
end
